### ISSUE TITLE
Boxed not working (1.17.1 / Purpur)

### ISSUE THREAD

**Issue by Bounser** [BentoBoxWorld/Boxed#30]
### Description
Boxed its not working in my server, using purpur 1.17.1, and all the addons/dependencies **up to date**.
#### Describe the bug
When I first load the server, it throws this error **https://pastebin.com/rZs328V3** _(With WorldGeneratorApi actually in his latest version)_
Then, using /boxed throws the error **https://pastebin.com/TjGbLAC5**
#### Steps to reproduce the behavior

Im just using the latests versions of all the required things. All in the last 1.17.1 purpur release.
### Environment
Java 16 / 1.17.1 purpur
##### Output of `/bbox version` (Mandatory)

```
Running PURPUR 1.17.1.
BentoBox version: 1.17.1
Database: JSON
 Loaded Game Worlds:
Loaded Addons:
Biomes 1.14.0 (DISABLED)
Border 3.2.0 (ENABLED)
Boxed 1.2.0 (ERROR)
Challenges 0.8.4 (DISABLED)
ControlPanel 1.13.0 (ENABLED)
InvSwitcher 1.11.0 (ENABLED)
IslandFly 1.8.1 (ENABLED)
Level 2.7.0 (ENABLED)
Likes 2.1.1 (ENABLED)
Limits 1.17.0 (ENABLED)
Visit 1.3.0 (ENABLED)

```

[Added stack traces for future reference]
```
[08:58:07] [Server thread/ERROR]: [BentoBox] java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.orElseThrow(Optional.java:377)
	at nl.rutgerkok.worldgeneratorapi.internal.bukkitoverrides.NoiseToTerrainGenerator.createNoiseSettings(NoiseToTerrainGenerator.java:71)
	at nl.rutgerkok.worldgeneratorapi.internal.bukkitoverrides.NoiseToTerrainGenerator.<init>(NoiseToTerrainGenerator.java:105)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorImpl.toBaseTerrainGenerator(WorldGeneratorImpl.java:241)
	at nl.rutgerkok.worldgeneratorapi.internal.recording.RecordingWorldGeneratorImpl.toBaseTerrainGenerator(RecordingWorldGeneratorImpl.java:129)
	at nl.rutgerkok.worldgeneratorapi.WorldGenerator.setBaseNoiseGenerator(WorldGenerator.java:114)
	at world.bentobox.boxed.generators.BoxedChunkGenerator.lambda$getGenerator$0(BoxedChunkGenerator.java:31)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorApiImpl.checkForCopiedWorldGenerator(WorldGeneratorApiImpl.java:75)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorApiImpl.lambda$getForWorld$1(WorldGeneratorApiImpl.java:111)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorApiImpl.getForWorld(WorldGeneratorApiImpl.java:110)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorApiImpl.onWorldAddOrRemove(WorldGeneratorApiImpl.java:183)
	at nl.rutgerkok.worldgeneratorapi.internal.WorldGeneratorApiImpl.lambda$injectWorldRemovalListener$2(WorldGeneratorApiImpl.java:158)
	at nl.rutgerkok.worldgeneratorapi.internal.ChangeListeningMap.put(ChangeListeningMap.java:64)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.addWorld(CraftServer.java:1284)
	at net.minecraft.server.level.WorldServer.<init>(WorldServer.java:584)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.createWorld(CraftServer.java:1182)
	at org.bukkit.Bukkit.createWorld(Bukkit.java:639)
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:384)
	at world.bentobox.boxed.Boxed.getWorld(Boxed.java:200)
	at world.bentobox.boxed.Boxed.createWorlds(Boxed.java:170)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:288)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:237)
	at world.bentobox.bentobox.BentoBox.completeSetup(BentoBox.java:186)
	at world.bentobox.bentobox.BentoBox.lambda$onEnable$0(BentoBox.java:172)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1210)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
	at java.base/java.lang.Thread.run(Thread.java:831)

[08:58:07] [Server thread/INFO]: [BentoBox] Enabling other addons...
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Level (2.7.0)...
[08:58:07] [Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : caveblock-world
[08:58:07] [Server thread/WARN]: [BentoBox] [Level] Level Addon: No such world in blockconfig.yml : acidisland_world
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Border (3.2.0)...
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Challenges (0.8.4)...
[08:58:07] [Server thread/INFO]: [BentoBox] [Challenges] Loading challenges...
[08:58:07] [Server thread/ERROR]: [BentoBox] [Challenges] Challenges could not hook into AcidIsland or BSkyBlock so will not do anything!
[08:58:07] [Server thread/INFO]: [BentoBox] Challenges is disabled.
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Likes (2.1.1)...
[08:58:07] [Server thread/INFO]: [BentoBox] Loading likes...
[08:58:07] [Server thread/WARN]: [BentoBox] [Likes] Warps addon not found by Likes Addon!
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Biomes (1.14.0)...
[08:58:07] [Server thread/ERROR]: [BentoBox] [Biomes] Biomes could not hook into any GameMode so will not do anything!
[08:58:07] [Server thread/INFO]: [BentoBox] Biomes is disabled.
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling IslandFly (1.8.1)...
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Limits (1.17.0)...
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Entity limits:
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Limit ENDERMAN to 5
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Limit CHICKEN to 10
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Entity group limits:
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Loading default limits
[08:58:07] [Server thread/INFO]: [BentoBox] [Limits] Limit HOPPER to 10
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling InvSwitcher (1.11.0)...
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling Visit (1.3.0)...
[08:58:07] [Server thread/INFO]: [BentoBox] Enabling ControlPanel (1.13.0)...
[08:58:07] [Server thread/INFO]: [BentoBox] Loading control panels...
[08:58:07] [Server thread/INFO]: [BentoBox] Addons successfully enabled.
[08:58:07] [Server thread/INFO]: [BentoBox] Hooking with Multiverse-Core...
[08:58:07] [Server thread/INFO]: [BentoBox] Hooking with dynmap...
[08:58:07] [Server thread/INFO]: [BentoBox] Hooking with WorldEdit...
[08:58:07] [Server thread/INFO]: 
  ____             _        ____
 |  _ \           | |      |  _ \             by tastybento and Poslovitch
 | |_) | ___ _ __ | |_ ___ | |_) | _____  __  2017 - 2020
 |  _ < / _ \ '_ \| __/ _ \|  _ < / _ \ \/ /
 | |_) |  __/ | | | || (_) | |_) | (_) >  <   v1.17.1
 |____/ \___|_| |_|\__\___/|____/ \___/_/\_\  Loaded in 1476ms.
```

**Comment by tastybento** [comment]
The error is coming from WorldGeneratorAPI plugin. Maybe there is an incompatibility with Purpur. Please confirm that you are running version 1.2.1? https://github.com/rutgerkok/WorldGeneratorApi/releases

**Comment by Bounser** [comment]
> The error is coming from WorldGeneratorAPI plugin. Maybe there is an incompatibility with Purpur. Please confirm that you are running version 1.2.1? https://github.com/rutgerkok/WorldGeneratorApi/releases

Yes, Im using the latest version (I also tried with the immediate past).
 So yes, its something with Purpur, because I tried replacing it with paper and now its working well. ¿What should I do now? Report this in the github of WorldGeneratorApi?

**Comment by tastybento** [comment]
Yes. You can ask if the author can consider support for Purpur, but is might not be something he can do.
