### ISSUE TITLE
Enderpearl bug and no meta data error

### ISSUE THREAD

**Issue by yooniks** [BentoBoxWorld/Boxed#91]
### Expected behavior

No errors, box moving when using enderpearls.

### Observed/Actual behavior

Box is not moved when using enderpearls, there are errors in console, when i use enderpearl then i can't teleport to my box because it says "cannot teleport outside of the box".

### Steps/models to reproduce

Use the newest versions..

### BentoBox version

2.5.0 BentoBox version and 2.7.1 Boxed version.

### Plugin list

[21:59:16 INFO]: Bukkit Plugins:
[21:59:16 INFO]:  - BentoBox, BentoBox-Boxed, Essentials, EssentialsSpawn, FastAsyncWorldEdit, ItemEdit, LuckPerms, PlaceholderAPI, Vault
[21:59:16 INFO]:  ViaBackwards, ViaVersion, *VoidWorld, WorldGuard

### Other

Enderpearl error:
```
[22:00:24 ERROR]: Could not pass event ProjectileHitEvent to BentoBox v2.5.0
java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.equals(Object)" because "this.location" is null
        at BentoBox-2.5.0.jar/world.bentobox.bentobox.database.objects.Island.setProtectionCenter(Island.java:1750) ~[BentoBox-2.5.0.jar:?]
        at Boxed-2.7.1-1723645696405.jar/world.bentobox.boxed.listeners.EnderPearlListener.moveBox(EnderPearlListener.java:117) ~[Boxed-2.7.1-1723645696405.jar:?]
        at Boxed-2.7.1-1723645696405.jar/world.bentobox.boxed.listeners.EnderPearlListener.lambda$onEnderPearlLand$2(EnderPearlListener.java:93) ~[Boxed-2.7.1-1723645696405.jar:?]
        at java.base/java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at Boxed-2.7.1-1723645696405.jar/world.bentobox.boxed.listeners.EnderPearlListener.lambda$onEnderPearlLand$4(EnderPearlListener.java:89) ~[Boxed-2.7.1-1723645696405.jar:?]
        at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at Boxed-2.7.1-1723645696405.jar/world.bentobox.boxed.listeners.EnderPearlListener.onEnderPearlLand(EnderPearlListener.java:83) ~[Boxed-2.7.1-1723645696405.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor424.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-14-9ab644e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1520) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.world.entity.projectile.Projectile.preHitTargetOrDeflectSelf(Projectile.java:215) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.world.entity.projectile.ThrowableProjectile.tick(ThrowableProjectile.java:49) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.world.entity.projectile.ThrownEnderpearl.tick(ThrownEnderpearl.java:133) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1248) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1420) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:737) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:717) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1806) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-14-9ab644e]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

Meta data handler error:
```
[21:56:44 WARN]: [BentoBox] No metadata handler found for v1_21_1_R0_1_SNAPSHOT in Boxed.
[21:56:44 WARN]: java.lang.ClassNotFoundException: world.bentobox.boxed.nms.v1_21_1_R0_1_SNAPSHOT.GetMetaData
[21:56:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197)
[21:56:44 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[21:56:44 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
[21:56:44 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[21:56:44 WARN]:        at java.base/java.lang.Class.forName(Class.java:534)
[21:56:44 WARN]:        at java.base/java.lang.Class.forName(Class.java:513)
[21:56:44 WARN]:        at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.forName(AbstractDefaultRulesReflectionProxy.java:68)
[21:56:44 WARN]:        at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.forName(Unknown Source)
[21:56:44 WARN]:        at Boxed-2.7.1-1723645696405.jar//world.bentobox.boxed.listeners.NewAreaListener.nmsData(NewAreaListener.java:631)
[21:56:44 WARN]:        at Boxed-2.7.1-1723645696405.jar//world.bentobox.boxed.listeners.NewAreaListener.processJigsaw(NewAreaListener.java:508)
[21:56:44 WARN]:        at Boxed-2.7.1-1723645696405.jar//world.bentobox.boxed.listeners.NewAreaListener.removeJigsaw(NewAreaListener.java:459)
[21:56:44 WARN]:        at Boxed-2.7.1-1723645696405.jar//world.bentobox.boxed.listeners.NewAreaListener.placeStructure(NewAreaListener.java:183)
[21:56:44 WARN]:        at Boxed-2.7.1-1723645696405.jar//world.bentobox.boxed.listeners.NewAreaListener.buildStructure(NewAreaListener.java:163)
[21:56:44 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[21:56:44 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[21:56:44 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1726)
[21:56:44 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473)
[21:56:44 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[21:56:44 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[21:56:44 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[21:56:44 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[21:56:44 WARN]: [BentoBox] No metadata handler found for v1_21_1_R0_1_SNAPSHOT in Boxed.
```

**Comment by tastybento** [comment]
You will need 2.5.1 BentoBox and the latest Boxed release for this fix.
